// @flow

export type UserProfile = {
  id?: any,
  state?: string,
  email?: any,
  profileType?: any,
  businessName?: string,
  firstName?: string,
  lastName?: string,
  birthDay?: string,
  birthMonth?: number,
  birthYear?: string,
  avatarUrl?: string | any,
  avatarData?: any,
  gender?: string,
  bio?: string,
  location?: string,
  latitude?: any,
  longitude?: any,
  zipCode?: string,
  city?: string,
  stateCode?: string,
  country?: string,
  education?: string,
  companyPosition?: string,
  tagList?: any[],
  antogonistTagList?: any[],
  visibility?: string,
  createdAt?: any,
  isFollowed?: boolean,
  levelOfConnect?: number,
  connectionsCount?: number,
  mutualConnectionsCount?: number,
  isSendRequest?: any,
  isReceiveRequest?: any,
  skin?: any
};

export type Reply = {
  id: any,
  content: string,
  location: string,
  updatedAt: string,
  createdAt: string,
  photos: any[],
  videos: any[],
  authorVisibility: string,
  user?: any,
  isMy?: boolean
};

export type Post = {
  id: any,
  content: string,
  location: string,
  updatedAt: string,
  createdAt: string,
  tagList: any[],
  isFollowed: boolean,
  isMy?: boolean,
  user?: any,
  photos: any[],
  videos: any[],
  replies?: Reply[],
  repliesCount: number,
  repost: Post,
  repostReply: Reply,
  authorVisibility: string
};
